### ISSUE TITLE
index！

### ISSUE THREAD

**Issue by CR7forMadrid** [Fried-Rice-Lab/EMT#2]
Hello, you are doing a great job! But is it possible to release the metrics obtained by training using only the DIV2K dataset? So that we can quote your work!

**Comment by Jinchen2028** [comment]
Thank you for your attention to our work, but our method uses the DF2K training and there is no DIV2K for now.

**Comment by CR7forMadrid** [comment]
How do I understand the paper and code: On the base of this work, we extended the idea and developed PM by improving it. Specifically, PM first divides the feature channels into five equal groups, then shifts the feature points of the first four groups in a specific order (left, right, top, bottom) and fill the blank pixels on the opposite side with those that are out of range.                   There are five groups mentioned here, but the code only divides the number of channels into four groups
