### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by epishchik** [Fried-Rice-Lab/EMT#5]
Hey! Can you please provide a single image inference script? I've written this one, but it seems like I made a mistake somewhere, because the generation quality is poor (ssim is around 0.5-0.6 for x4 configuration on my data, data isn't anything specific, for example pretrained Real-ESRGAN gives ssim around 0.8-0.9).

```python
# create IRModel
model = IRModel(opt)
# extract generator, device and data number of bits
net_g, device, nbits = model.net_g, model.device, model.bit
# turn off gradient calculations and set eval mode
net_g.eval()
for param in net_g.parameters():
    param.requires_grad = False

# cv2 image to torch.tensor
inp_tensor = img2tensor(img).unsqueeze(0).to(device)
# get prediction using generator and convert to (h, w, c) format
out_img = (
    net_g(inp_tensor)
    .squeeze(0)
    .detach()
    .cpu()
    .clamp(0, 2**nbits - 1.0)
    .round()
    .numpy()
    .transpose(1, 2, 0)
).astype(np.uint8)
# convert color scheme
out_img = cv2.cvtColor(out_img, cv2.COLOR_BGR2RGB)
```

**Comment by liozur** [comment]
Sorry for the late reply.

A possible alternative would be to put the single images in a folder as well, and treat it as a dataset containing only the single images.

I haven't looked closely at your code, but I'm guessing it might have something to do with data type conversion. I had a lot of trouble with this when I was writing the code.

**Comment by epishchik** [comment]
Got it, I think the script above is valid and the issues are on my side.
