### ISSUE TITLE
How to setup inference for a single LR image

### ISSUE THREAD

**Issue by pvtoan** [Fried-Rice-Lab/EMT#7]
Hi,

I am able to run your code test.py with your default settings in *.yml file.

However, in the real test, only a single LR image should be provided, instead of giving both LR and HR as in training process.
    dataroot_gt: datasets/demo_data/Demo_Set5/HR/x4
    dataroot_lq: datasets/demo_data/Demo_Set5/LR/x4

Therefore, can you please tell me how to do inference giving only a single LR image?

**Comment by liozur** [comment]
https://github.com/Fried-Rice-Lab/FriedRiceLab/issues/20

https://github.com/Fried-Rice-Lab/EMT/issues/5

**Comment by pvtoan** [comment]
Hi,

Thank you for your reply!

I think we have some misunderstanding matter.

Actually, what I means is that, your code has a validation part and it will compute the metric between given LR and HR images. Meanwhile, I need to test how good EMT works on real-world images. It means, I cannot provide the path for HR images because real-world images don't have.

I think your code "test.py" currently supports for researchers who want to do quantitative comparisons on synthetic datasets.

**Comment by liozur** [comment]
Sorry :(

Please check [infer.py](https://github.com/Fried-Rice-Lab/FriedRiceLab/blob/master/infer.py).

**Comment by pvtoan** [comment]
I used infer.py with the same command to run:
python infer.py -expe options/EMT.yml -task options/LSR_x4.yml

However, I got this problem
'IRModel' object has no attribute 'nondist_inference'

**Comment by liozur** [comment]
This repository does not have all the features.

Please check https://github.com/Fried-Rice-Lab/FriedRiceLab/pull/17 to use the infer feature.

**Comment by pvtoan** [comment]
I think I already fixed the problem.

Actually, "nondist_inference" should be "nondist_validation". 

Also, model.nondist_inference(infer_loader) --> model.nondist_validation(infer_loader) missed other 3 arguments including current_iter, tb_logger, save_img.

If I'm correct, please check your code carefully. Otherwise, please correct me.

Thank you so much for your contributions on SR!

**Comment by liozur** [comment]
:)
