### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Qqsoe** [Fried-Rice-Lab/EMT#8]
作者您好，数据集下载失败，请问还有其他的下载渠道吗

**Comment by liozur** [comment]
请问下载成功了吗?

放置数据集的那个 MicroSoft 账号已经很久没有用了, 但是我前一段时间测试还是可以下载的.

如果仍然无法下载, 你可以去数据集的官网下载, 然后按照 BasicSR Doc 中的指导处理一下. 这一块的代码我们没有修改.

**Comment by Qqsoe** [comment]
感谢回复，已经下载成功
