### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Qqsoe** [Fried-Rice-Lab/EMT#9]
size mismatch for tail.0.weight: copying a param with shape torch.Size([12, 60, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 60, 3, 3]).
        size mismatch for tail.0.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([48]).
请问训练时遇到这个问题怎么解决呢

**Comment by liozur** [comment]
这个应该是你加载的 checkpoint 与 arch 不匹配。
检查下 config 文件。

**Comment by Qqsoe** [comment]
感谢，问题已经解决，但是运行后一直2024-04-29 17:26:20,143 INFO: Start training from epoch: 0, iter: 0，为什么不往下进行呢

**Comment by liozur** [comment]
>感谢，问题已经解决，但是运行后一直2024-04-29 17:26:20,143 INFO: Start training from epoch: 0, iter: 0，为什么不往下进行呢

可能是这一 item 还没结束，当然不更新下一 item 的数据。
